---
- name: Palo Alto Create Firewall Policies
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    PYTHONHTTPSVERIFY: 0
  vars:
    provider: '{"api_key": "{{ palo_api_key }}", "ip_address": "{{ palo_fw_ip }}"}'

  tasks:
  - name: Add Rules at Specific Location in the Rule Base
    include_role:
      name: create_security_policies
      vars_from: "password.yml"
