---
- name: Create Host Record
  hosts: "{{ grid_manager }}"
  connection: local
  gather_facts: false

  tasks:
  - name: Create Host Record
    include_role:
      name: create_host_record
      vars_from: "secrets.yml"
