---
- name: Create Windows 2012r2 VM from Template and Customize
  vmware_guest:
    datacenter: "{{ vm_datacenter }}"
    validate_certs: False
    folder: "/{{ vm_datacenter }}/vm"
    name: "{{ windows_vm_hostname }}"
    state: present
    template: "{{ vm_template }}"
    disk:
    - size_gb: "{{ vm_disk_size }}"
      type: "{{ vm_disk_type }}"
      datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: "{{ vm_ram }}"
      num_cpus: "{{ vm_cpu }}"
    networks:
    - name: "{{ vm_network }}"
      ip: "{{ windows_vm_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway_ip }}"
      dns_servers:
      - "{{ vm_dns_server }}"
    wait_for_ip_address: yes
    customization:
      autologon: yes
      domain: "{{ vm_domain }}"
      dns_servers:
      - "{{ vm_dns_server }}"
      hostname: "{{ windows_vm_hostname }}"
      password: "{{ win_vm_password }}"
  delegate_to: localhost

- name: Wait for VM to be ready
  wait_for: timeout=300
  delegate_to: localhost

- name: Sending notification email
  mail:
    host: localhost
    port: 25
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: Ansible-report
    body: "{{ windows_vm_hostname }} has been successfully provisioned"
  delegate_to: localhost
