---
- name: Create Fortigate Firewall Policy
  fortios_ipv4_policy:
    host: "{{ fortigate_firewall[inventory_hostname]['host_ip'] }}"
    username: "{{ fortigate_username }}"
    password: "{{ fortigate_password }}"
    id: "{{ fortigate_firewall[inventory_hostname]['policy_id'][item] }}"
    src_addr: "{{ fortigate_firewall[inventory_hostname]['source'][item] }}"
    dst_addr: "{{ fortigate_firewall[inventory_hostname]['destination'][item] }}"
    service: "{{ fortigate_firewall[inventory_hostname]['services'] }}"
    state: 'present'
    policy_action: "{{ fortigate_firewall[inventory_hostname]['policy'] }}"
  loop: "{{ range(0, fortigate_firewall[inventory_hostname]['destination']|length)|list }}"

- name: Create Fortigate Firewall Policy in Reverse Direction
  fortios_ipv4_policy:
    host: "{{ fortigate_firewall[inventory_hostname]['host_ip'] }}"
    username: "{{ fortigate_username }}"
    password: "{{ fortigate_password }}"
    id: "{{ fortigate_firewall[inventory_hostname]['inverse_policy_id'][item] }}"
    src_addr: "{{ fortigate_firewall[inventory_hostname]['destination'][item] }}"
    dst_addr: "{{ fortigate_firewall[inventory_hostname]['source'][item] }}"
    service: "{{ fortigate_firewall[inventory_hostname]['services'] }}"
    state: 'present'
    policy_action: "{{ fortigate_firewall[inventory_hostname]['policy'] }}"
  loop: "{{ range(0, fortigate_firewall[inventory_hostname]['destination']|length)|list }}"
