---
- name: Search Windows Update
  hosts: all
  gather_facts: false
  tasks:
  - name: Search and return list of found updates
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      state: searched
      log_path: C:\ansible_wu.txt
