--- 
- 
  gather_facts: false
  hosts: all
  name: "Windows Update"
  tasks: 
    - 
      log_path: "C:\\ansible_wu.txt"
      name: "Search for Windows Updates then log to C:\\ansible_wu.txt"
      state: searched
      win_updates: 
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - DefinitionUpdates
