- name:  Install IIS server
  hosts: all
  gather_facts: false
  tasks:
      - name: Install IIS Web-Server with sub features and management tools
        win_feature:
          name: Web-Server
          state: present
          include_sub_features: True
          include_management_tools: True
        register: res
          
      - name: Reboot if installing Web-Server feature requires it
        win_reboot:
        when: res.reboot_required
