---
- name: "Windows Join To Domain"
  hosts: all
  tasks:
    - name: "Join Domain"
      win_domain_membership:
        dns_domain_name: "{{ domain }}"
        hostname: "{{ compname }}"
        domain_admin_user: "{{ domadmin }}"
        domain_admin_password: "{{ pass }}"
        state: domain
      register: domain_state
    - win_reboot:
      when: domain_state.reboot_required
