---
- name: Expand VM Disk
  vmware_guest:
    datacenter: "{{ vm_datacenter }}"
    validate_certs: False
    folder: "/{{ vm_datacenter }}/vm"
    name: "{{ windows_vm_hostname }}"
    state: present
    template: "{{ vm_template }}"
    disk:
      - size_gb: "{{ vm_disk1_size }}"
        type: "{{ vm_disk_type }}"
        datastore: "{{ vm_datastore }}"
      - size_gb: "{{ vm_disk2_size }}"
        type: "{{ vm_disk_type }}"
        datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: "{{ vm_ram }}"
      num_cpus: "{{ vm_cpu }}"
    networks:
    - name: "{{ vm_network }}"
      ip: "{{ windows_vm_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway_ip }}"
      dns_servers:
      - "{{ vm_dns_server }}"
    wait_for_ip_address: yes
    customization:
      autologon: yes
      domain: "{{ vm_domain }}"
      dns_servers:
      - "{{ vm_dns_server }}"
      hostname: "{{ windows_vm_hostname }}"
      password: "{{ win_vm_password }}"
