---
fortigate_firewall:
  fortigate_fw_192.168.200.100:
    host_ip: '192.168.200.100'
    policy_id: '10'
    inverse_policy_id: '11'
    source: 'network_zone_1'
    destination: 'network_zone_9'
    services: ['HTTP', 'HTTPS', 'SSH', 'TOMCAT']
    policy: 'accept'
  fortigate_fw_192.168.30.100:
    host_ip: '192.168.30.100'
    policy_id: '20'
    inverse_policy_id: '21'
    source: 'network_zone_3'
    destination: 'network_zone_6'
    services: ['HTTP', 'HTTPS', 'SSH']
    policy: 'accept'
