---
- name: Create ACL (Bi-directional)
  ios_config:
    lines:
      - "permit ip {{ ip_mask.src_ip[item|int] }} {{ ip_mask.src_mask[item|int] }} {{ ip_mask.dest_ip[item|int] }} {{ ip_mask.dest_mask[item|int] }}"
      - "permit ip {{ ip_mask.dest_ip[item|int] }} {{ ip_mask.dest_mask[item|int] }} {{ ip_mask.src_ip[item|int] }} {{ ip_mask.src_mask[item|int] }}"
    parents: "ip access-list extended {{ ip_access_list }}"
  loop:
  - { src_ip: "{{ source_ip_segment.split(',') }}", src_mask: "{{ source_ip_segment_mask.split(',') }}", dest_ip: "{{ destination_ip_segment.split(',') }}", dest_mask: "{{ destination_ip_segment_mask.split(',') }}" }
  loop_control:
    loop_var: ip_mask
