---
- name: Create Network
  nios_network:
    network: "{{ network }}"
    network_view: "{{ network_view }}"
    extattrs:
      Site: "{{ site_info }}"
    comment: "{{ network_comments }}"
    state: present
    provider: "{{ nios_provider }}"
