---
- name: Create new address objects in Fortinet Firewall
  hosts: "{{ fortinet_firewall_ip }}"
  gather_facts: True
  vars:
    number_of_ip_segments: "{{ ip_segment_server.split(',') | length }}"

  tasks:
  - name: Register New Address
    include_role:
      name: fortinet_create_new_address_object
      vars_from: "password.yml"
