---
- name: Update Fortinet Firewall Rule
  hosts: "{{ fortinet_firewall_ip }}"
  gather_facts: True
  vars:
    number_of_address_segments: "{{ source_address.split(',') | length }}"
    random_id: "{{ 1000 | random }}"

  tasks:
  - name: Update ACL
    include_role:
      name: fortinet_update_firewall_rule
      vars_from: "password.yml"
