---
- name: Create Security Rule
  panos_security_rule:
    ip_address: "{{ hostvars[firewall_node].ansible_host }}"
    username: "{{ paloalto_username }}"
    password: "{{ paloalto_password }}"
    operation: "{{ firewall_operation }}"
    rule_name: "{{ firewall_rule_name }}"
    source_ip: "{{ srcipaddress }}"
    source_user: 'any'
    destination_ip: "{{ dstipaddress }}"
    category: 'any'
    application: "{{ application }}"
    service: "{{ service }}"
    hip_profiles: 'any'
    action: "{{ firewall_action }}"
    devicegroup: "{{ device_group }}"
  delegate_to: localhost
