---
- name: Add Pool Members
  bigip_pool_member:
    provider: "{{ f5_provider }}"
    state: present
    partition: Common
    host: "{{ hostvars[item].ansible_host }}"
    name: "{{ hostvars[item].inventory_hostname }}"
    port: "{{ webapp_port }}"
    pool: "{{ f5_pool_name }}"
    description: "{{ webapp_description }}"
    validate_certs: no
  loop: "{{ webapp_servers }}"
  delegate_to: localhost
