---
- name: Perform Application Verification
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: yes

  tasks:
  - name: Perform Application Verification
    include_role:
      name: "rhel_verification"
