---
- block:
  - name: Get Access Token for DC-1
    k8s_auth:
      host: "{{ ocp1_api_endpoint }}"
      username: "{{ oc_user }}"
      password: "{{ oc_password }}"
      validate_certs: no
    no_log: true
    register: oc_token_dc1
    delegate_to: localhost

  - name: Get Access Token for DC-2
    k8s_auth:
      host: "{{ ocp2_api_endpoint }}"
      username: "{{ oc_user }}"
      password: "{{ oc_password }}"
      validate_certs: no
    no_log: true
    register: oc_token_dc2
    delegate_to: localhost

  - name: OC Login to DC-2
    command: "/usr/bin/oc login --insecure-skip-tls-verify -u {{ oc_user }} -p {{ oc_password }} {{ ocp2_api_endpoint }}"
    no_log: true

  - name: "Check if project {{ oc_project }} exits"
    command: "/usr/bin/oc get project {{ oc_project }}"
    ignore_errors: yes
    register: get_app_dc2

  - name: Copy Image from DC-1 to DC-2
    shell: "skopeo copy docker{% raw %}:{% endraw %}//{{ ocp1_integrated_registry }}/{{ oc_project }}/{{ oc_app }} docker{% raw %}:{% endraw %}//{{ ocp2_integrated_registry }}/{{ oc_project }}/{{ oc_app }} --src-creds {{ oc_user }}{% raw %}:{% endraw %}{{ oc_token_dc1.k8s_auth.api_key }} --dest-creds {{ oc_user }}{% raw %}:{% endraw %}{{ oc_token_dc2.k8s_auth.api_key }} --dest-tls-verify=false --src-tls-verify=false"
  when: prom_data.json.data.result[0].value[1] | float('inf') > cpu_threshold and check_dc2_app.stdout == ""
