---
- name: Return next available IP addresses for network "{{ ipam_network }}", excluding gateway IPs
  set_fact:
    ipaddr: "{{ lookup('nios_next_ip', ipam_network, exclude=subnet_gateway.split(','),
                provider=nios_provider) }}"

- name: Print next available IP
  debug:
    var: ipaddr

- name: Save information of next available IP for subsequent workflow
  set_stats:
    data:
      ipv4_address: "{{ ipaddr }}"
