---
- name: Check Cisco Router Config Drift
  hosts: "{{ cisco_router }}"
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Check Config Drift
    include_role:
      name: cisco_config_drift_check
      vars_from: "secrets.yml"
