---
- name: Generate Web App Hostname in List Format
  set_fact:
    vm_hostname: "{{ hostname.split(',') }}"

- name: Remove Nodes
  bigip_node:
    provider: "{{ f5_provider }}"
    name: "{{ hostvars[item].inventory_hostname }}"
    state: absent
    validate_certs: "no"
  loop: "{{ vm_hostname }}"
  delegate_to: localhost

- name: Save information of Web App Hostname for subsequent workflow
  set_stats:
    data:
      webapp_servers: "{{ vm_hostname }}"
