---
- name: Update State (to Review) and Work Notes of Change Request
  snow_record:
    username: "{{ servicenow_username }}"
    password: "{{ servicenow_password }}"
    instance: "{{ servicenow_instance }}"
    state: present
    number: "{{ change_request_id }}"
    table: "{{ servicenow_table }}"
    data:
      state: 0
      work_notes : "{{ change_request_id }} has been successfully implemented by Ansible"
  delegate_to: localhost
