---
- name: Add Pool
  bigip_pool:
    provider: "{{ f5_provider }}"
    state: present
    name: "{{ f5_pool_name }}"
    partition: Common
    lb_method: "{{ f5_lb_method }}"
    monitors: "{{ f5_monitors }}"
    monitor_type: "and_list"
    validate_certs: no
  delegate_to: localhost
