---
- name: Remove OCP-2 Reference from HA Proxy
  hosts: haproxy1
  gather_facts: false

  tasks:
  - name: Remove OCP-2 Configurations from HA Proxy
    lineinfile:
      path: /etc/haproxy/haproxy.cfg
      state: absent
      line: "    server {{ app_service }}-{{ oc_project }}.apps.{{ ocp_cluster2 }} {{ app_service }}-{{ oc_project }}.apps.{{ ocp_cluster2 }}:{{ app_service_port }} check"
    notify: restart haproxy

  handlers:
  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
