---
- name: OCP Cloudburst Initial Setup
  hosts: ocp1_bastion
  become: true
  gather_facts: false

  tasks:
  - name: OCP Cloudburst Initial Setup
    include_role:
      name: ocp_cloudburst_inital_setup
      vars_from: "password.yml"
