---
- name: Continuous Deployment
  hosts: ocp1_bastion
  gather_facts: false

  tasks:
  - name: Continuous Deployment
    include_role:
      name: ocp_cloudburst_continuous_deployment
      vars_from: "password.yml"
