---
- name: OCP Application Deployment
  hosts: ocp2_bastion
  gather_facts: false

  tasks:
  - name: Application Deployment
    include_role:
      name: ocp_cloudburst_deploy_app
      vars_from: "password.yml"
