---
- name: Create DNS View
  nios_dns_view:
    name: "{{ dns_view }}"
    network_view: "{{ network_view }}"
    extattrs:
      Site: "{{ site_info }}"
    comment: "{{ dns_view_comments }}"
    state: present
    provider: "{{ nios_provider }}"
