---
- name: Update index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644
  notify: "restart httpd service"
  when: request_number is search("REQ")

- name: Capture information of request number and request item number for subsequent workflow
  set_stats:
    data:
      request_number: "{{ request_number }}"
      req_item_number: "{{ req_item_number }}"
  when: request_number is search("REQ")
