---
# Refer to https://www.cisco.com/c/en/us/td/docs/routers/csr1000/software/configuration/b_CSR1000v_Configuration_Guide/b_CSR1000v_Configuration_Guide_chapter_01001.pdf
# on how to perform upgrade on Cisco CSR 1000v Router
- name: Print List of all Files and Directories in bootflash Memory 
  ios_command:
    commands: 'dir bootflash:'

- name: Delete all Entries in Bootable Image list
  ios_config:
    lines: 'no boot system'

- name: Set Upgrade Image as Boot image
  ios_config:
    lines: 'boot system bootflash:/{{ new_system_image }}'

- name: Updates GRUB menu list of images available on the bootflash disk
  ios_command:
    commands: 'write memory'

- name: Ensure router loads system image from boot system commands in startup config
  ios_config:
    lines: 'config-register 0x2102'

- name: Copy Running Config to Startup Config
  ios_command:
    commands:
      - command: 'copy running-config startup-config'
        prompt: 'Destination filename \[startup-config\]'
        answer: "\r"

- name: Write Memory
  ios_command:
    commands: 'write memory'

- name: Reload
  ios_command:
    commands:
      - command: 'reload'
        prompt: 'Proceed with reload\? \[confirm\]'
        answer: 'y'

- name: Wait for Reload to Complete
  wait_for:
    host: "{{ cisco_router }}"
    port: "{{ ssh_port }}"
    delay: "{{ wait_time_before_checking }}"
    timeout: "{{ wait_time_after_reboot }}"
  connection: network_cli

- name: Send Email with Report
  mail:
    host: smtp.gmail.com
    port: 465
    username: "{{ gmail_account }}"
    password: "{{ gmail_account_password }}"
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: "Ansible Report"
    body: "{{ inventory_hostname }} has been upgraded with new boot image {{ new_system_image }}"
  delegate_to: localhost
  run_once: yes
