---
- name: install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest

- name: enable {{ payload }} at boot
  service:
    name: "{{ payload }}"
    enabled: yes

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644

- name: restart tomcat
  service:
    name: "{{ payload }}"
    state: restarted
