---
- name: Palo Alto Create Address Object
  hosts: "{{ firewall_node }}"
  gather_facts: false
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
  - name: Create PANOS Address Object
    include_role:
      name: create_panos_object
      vars_from: "password.yml"
