---
- name: F5 BIG-IP Remove Virtual Server
  hosts: lb
  gather_facts: false

  tasks:
  - name: Remove Virtual Server
    include_role:
      name: lb_remove_virtual_server
      vars_from: "secrets.yml"
