---
- name: Palo Alto Firewall Readiness Check and Backup
  hosts: "{{ firewall_node }}"
  gather_facts: false
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
  - name: Readiness Check and Backup
    include_role:
      name: panos_readiness_check_backup
      vars_from: "password.yml"
