---
- name: Validation Test
  hosts: "{{ webapp_servers }}"
  become: yes
  gather_facts: true

  tasks:
  - name: Validation test
    uri:
      url: http://127.0.0.1 
      return_content: yes
    register: webapp_result
    failed_when: "'Red Hat Ansible Automation' not in webapp_result.content" 
