---
- name: Add Virtual Server
  bigip_virtual_server:
    provider: "{{ f5_provider }}"
    state: present
    name: "{{ f5_virtual_server }}"
    partition: Common
    destination: "{{ hostvars['f5_bigip'].private_ip }}"
    port: 443
    enabled_vlans: all
    all_profiles: ['http','clientssl','oneconnect']
    pool: "{{ f5_pool_name }}"
    snat: Automap
    validate_certs: no
  delegate_to: localhost
