---
- name: Query Table
  block:
    - shell:
        cmd: |
          sqlplus -s /nolog << EOF
          connect {{ db_user }}/{{ db_password }}
          set linesize 10000
          set tab off
          set wrap off
          {{ db_action }} {{ db_columns }} from {{ db_table }};
          quit
          EOF
      register: query_output

    - name: Fail if Error
      fail:
        msg: "Error Detected - {{ query_output.stdout_lines }}"
      when: '"ERROR" in query_output.stdout'

    - name: Print Table Query Output
      debug:
        msg: "{{ query_output.stdout_lines }}"
  when: db_action == "select"

- name: Query Table - Order By
  block:
    - shell:
        cmd: |
          sqlplus -s /nolog << EOF
          connect {{ db_user }}/{{ db_password }}
          set linesize 10000
          set tab off
          set wrap off
          {{ db_action }} {{ db_columns }} from {{ db_table }} order by {{ column_ordering }};
          quit
          EOF
      register: query_output

    - name: Fail if Error
      fail:
        msg: "Error Detected - {{ query_output.stdout_lines }}"
      when: '"ERROR" in query_output.stdout'

    - name: Print Table Query Output
      debug:
        msg: "{{ query_output.stdout_lines }}"
  when: db_action == "select" and column_ordering is defined

- name: Describe Table
  block:
    - shell:
        cmd: |
          sqlplus -s /nolog << EOF
          connect {{ db_user }}/{{ db_password }}
          set tab off
          {{ db_action }} {{ db_table }};
          quit
          EOF
      register: describe_output

    - name: Fail if Error
      fail:
        msg: "Error Detected - {{ describe_output.stdout_lines }}"
      when: '"ERROR" in describe_output.stdout'

    - name: Print Describe Table Output
      debug:
        msg: "{{ describe_output.stdout_lines }}"
  when: db_action == "describe"
