---
- name: Firewall Policy Management
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    policy_id: 3
    target_policy_id: 4
    move_action: "before"

  tasks:
  - name: Create and move firewall policy to desired position
    include_role:
      name: create_and_move_policy_to_desired_position
      vars_from: "secrets.yml"
