---
- name: Create Address Object using API Key
  panos_object:
    ip_address: "{{ hostvars[firewall_node].ansible_host }}"
    api_key: "{{ paloalto_key }}"
    addressobject: "{{ address_object_name }}"
    operation: 'add'
    address: "{{ object_address }}"
    address_type: 'ip-netmask'
    description: "{{ object_description }}"
  delegate_to: localhost
