---
- name: Backup current running config
  ios_config:
    backup: yes

- name: Parse csv change request file
  csv_to_yaml:
    name: roles/cisco_add_acl/files/acl_requirements.csv
  register: csv_parse_results
  run_once: true
  delegate_to: localhost

- name: Create ACL config yaml file
  template:
    src: templates/cisco_acl_template.j2
    dest: /tmp/acl_config_update.yml
  run_once: true
  delegate_to: localhost

- name: Include vars from acl_config_update.yml
  include_vars:
    file: /tmp/acl_config_update.yml
  delegate_to: localhost

- include_tasks: update_acl_loop.yml
  loop: "{{ range(0, cisco_routers_acl|length)|list }}"
  loop_control:
    loop_var: entry_index

- name: Save running config to startup when modified
  ios_config:
    save_when: modified

- name: Clean up temporary acl_config_update.yml
  file:
    path: /tmp/acl_config_update.yml
    state: absent
  run_once: true
  delegate_to: localhost
