---
- name: Rescan Current Status of Storage
  win_shell: Update-HostStorageCache

- name: Expand Windows Hard Disk
  win_shell: |
    $size = Get-PartitionSupportedSize -DriveLetter {{ win_drive }}
    Resize-Partition -DriveLetter {{ win_drive }} -Size $size.SizeMax
