---
- name: Expand VMWare VM Hard Disk
  hosts: localhost
  gather_facts: False

  tasks:
  - name: Expand VMWare VM Hard Disk
    include_role:
      name: vmware_vm_disk_expansion
      vars_from: "password.yml"
