---
- name: Oracle Database 11g Express 11.2.0.2.0 Backup
  hosts: "{{ oracle_db }}"
  gather_facts: True
  environment:
    ORACLE_HOME: "{{ db_home }}"
    PATH: "{{ db_path }}"
    ORACLE_SID: "{{ db_sid }}"

  tasks:
  - name: Backup Oracle DB
    include_role:
      name: oracle_db_backup
      vars_from: "password.yml"
