---
- name: Oracle Database 11g Express 11.2.0.2.0 Manage Table Entries
  hosts: "{{ oracle_db }}"
  gather_facts: True
  environment:
    ORACLE_HOME: "{{ db_home }}"
    PATH: "{{ db_path }}"
    ORACLE_SID: "{{ db_sid }}"

  tasks:
  - name: Manage Table Entries
    include_role:
      name: oracle_manage_table
      vars_from: "password.yml"
