---
- name: Create Host Records
  nios_host_record: 
    name: "{{ webapp_servers[item] }}.{{ vm_domain }}"
    view: "{{ dns_view }}"
    ipv4:
      - address: "{{ ipv4_address[item] }}"
    ttl: 3600
    extattrs:
      Site: "{{ site_info }}"
    comment: "{{ host_record_comments }}"
    state: present
    provider: "{{ nios_provider }}"
  loop: "{{ range(0, webapp_servers|length)|list }}"
