---
- name: Create a virtual machine from Template and Customize
  vmware_guest:
    datacenter: "{{ vm_datacenter }}"
    validate_certs: False
    folder: "/{{ vm_datacenter }}/vm"
    name: "{{ vm_hostname }}"
    state: poweredon
    template: "{{ vm_template }}"
    disk:
    - size_gb: "{{ vm_disk_size }}"
      type: thin
      datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: "{{ vm_ram }}"
      num_cpus: "{{ vm_cpu }}"
    networks:
    - name: "{{ vm_network }}"
      ip: "{{ linux_vm_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway_ip }}"
    wait_for_ip_address: yes
    customization:
      domain: "{{ vm_domain }}"
      dns_servers:
      - "{{ vm_dns_server }}"
      hostname: "{{ vm_hostname }}"
  delegate_to: localhost

- name: Wait for system to become reachable over SSH
  wait_for_connection:
    timeout: 300

- name: Sending notification email
  mail:
    host: localhost
    port: 25
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: Ansible-report
    body: "{{ vm_hostname }} has been successfully provisioned"
  delegate_to: localhost
