---
# For some reasons, the config drift functionalities for ios_config module
# did not work properly for my environment in ansible 2.7.1 (it always states
# that there is no configuration changes even when there is). The ideal approach
# should really be ito simply make use of the ios_config module, i.e.
#
#- name: check the running-config against master config
#  ios_config:
#    diff_against: intended
#    intended_config: "{{ lookup('file', 'golden.cfg') }}"
#  register: config_drift
#
# I had to make use of the diff module from https://github.com/cytopia/ansible-modules
# to get similar results. I think this module has the added benefits to present things
# like which lines were added/removed, similar to git status.
#
#
- name: Gather Facts
  ios_facts:

- name: Get running config
  ios_command:
    commands: show running-config
  register: current_running_config

- name: Check for Configuration Drift
  vars:
    intended_config: "{{ inventory_hostname }}_golden.cfg"
  gen_diff:
    source: "{{ current_running_config.stdout[0] }}"
    target: "{{ lookup('file', intended_config) }}"
    source_type: string
    target_type: string
  register: config_drift

- name: Clean Up Reports Directory if it exists
  file:
    path: reports
    state: absent
  delegate_to: localhost
  run_once: yes

- name: Create Reports Directory
  file:
    path: reports
    state: directory
    mode: 0755
  delegate_to: localhost
  run_once: yes

- name: Gather facts of localhost to get current time/date
  setup:
    gather_subset: 'min'
  delegate_to: localhost

- name: Render Template
  template:
    src: templates/config_drift_template.txt.j2
    dest: "reports/{{ inventory_hostname }}_config_drift_report.txt"
  delegate_to: localhost

- name: Remove Non Config Lines from the report
  lineinfile:
    path: "reports/{{ inventory_hostname }}_config_drift_report.txt"
    state: absent
    line: '{{ item }}'
  loop:
    - '+Building configuration...'
    - '--- '
    - '+++ '
    - '-!         '
    - '+!'
    - '+'
  delegate_to: localhost

- name: Remove Special Characters from the report
  lineinfile:
    path: "reports/{{ inventory_hostname }}_config_drift_report.txt"
    state: absent
    regexp: '^@@(.*)$'
  delegate_to: localhost
                                  
- name: Remove Unchanged Configurations from the report
  lineinfile:
    path: "reports/{{ inventory_hostname }}_config_drift_report.txt"
    state: absent
    regexp: '^ (.*)$'
  delegate_to: localhost

- name: Remove Information on Config File Size from the report
  lineinfile:
    path: "reports/{{ inventory_hostname }}_config_drift_report.txt"
    state: absent
    regexp: "^(.*)Current configuration :(.*)$"
  delegate_to: localhost

- name: Consolidate Final Report
  assemble:
    src: reports/
    dest: reports/Consolidated_Config_Drift_Report.txt
  delegate_to: localhost
  run_once: yes

- name: Send Email with Report
  mail:
    host: smtp.gmail.com
    port: 465
    username: "{{ gmail_account }}"
    password: "{{ gmail_account_password }}"
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: "Ansible Report"
    body: "The consolidated configuration drift report for the Cisco Routers can be found in the attached file"
    attach:
     - reports/Consolidated_Config_Drift_Report.txt
  delegate_to: localhost
  run_once: yes
