---
- name: ServiceNow and Palo Alto
  hosts: "{{ firewall_node }}"
  gather_facts: False
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
  - name: ServiceNow and Palo Alto
    include_role:
      name: servicenow_panos_firewall
      vars_from: "password.yml"
