---
- name: Palo Alto Firewall
  hosts: "{{ firewall_node }}"
  gather_facts: False
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
  - name: Update Firewall Rule
    include_role:
      name: update_panos_rule
      vars_from: "password.yml"
