---
- name: Parse firewall address object csv file
  csv_to_yaml:
    name: roles/fortigate_create_address_object/files/firewall_objects.csv
  register: address_object_csv_parse_results

- name: Rollback address object
  fortios_address:
    host: "{{ hostvars[address_object_csv_parse_results['yaml_output']['nodes'][item]['firewall']].ansible_host }}"
    username: "{{ fortigate_username }}"
    password: "{{ fortigate_password }}"
    state: absent
    name: "{{ address_object_csv_parse_results['yaml_output']['nodes'][item]['object'] }}"
  loop: "{{ range(0, address_object_csv_parse_results['yaml_output']['nodes']|length)|list }}"
  when: address_object_csv_parse_results['yaml_output']['nodes'][item]['firewall'] == inventory_hostname
